// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO6K63mWRoaqQveBV_3EHq4vvdm3_Zetc',
    appId: '1:1066813291711:web:282bf7137d14f4c0e49a0a',
    messagingSenderId: '1066813291711',
    projectId: 'chat-app-84070',
    authDomain: 'chat-app-84070.firebaseapp.com',
    storageBucket: 'chat-app-84070.appspot.com',
    measurementId: 'G-Y2RYCP61EY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHv5SADjPtDGDpgKH30cE4vng5aKeAySc',
    appId: '1:1066813291711:android:b32433cf39de7453e49a0a',
    messagingSenderId: '1066813291711',
    projectId: 'chat-app-84070',
    storageBucket: 'chat-app-84070.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGkE90TQtWQlGJ7hpdm2z6GubPBaPzdg4',
    appId: '1:1066813291711:ios:0cab1a73894c1819e49a0a',
    messagingSenderId: '1066813291711',
    projectId: 'chat-app-84070',
    storageBucket: 'chat-app-84070.appspot.com',
    iosClientId: '1066813291711-2gvesonj06ujo1mcd4qfdndf5q7hmnuv.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGkE90TQtWQlGJ7hpdm2z6GubPBaPzdg4',
    appId: '1:1066813291711:ios:0cab1a73894c1819e49a0a',
    messagingSenderId: '1066813291711',
    projectId: 'chat-app-84070',
    storageBucket: 'chat-app-84070.appspot.com',
    iosClientId: '1066813291711-2gvesonj06ujo1mcd4qfdndf5q7hmnuv.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
